// Curated medical term bank, grouped by the same field names used on the
// frontend (see the `cats` array in app.js — keep these in sync).
//
// This bank powers two things:
//  1. /api/generate-words — used whenever GROQ_API_KEY isn't set, or the AI
//     call fails/times out/returns something unusable, so the puzzle can
//     always be built.
//  2. /api/explain-term — checked first (fast, free, always available)
//     before falling back to the AI for a term this list doesn't cover.

export const CATEGORY_WORDS = {
  Anatomy: [
    { word: 'FEMUR', definition: 'The long bone of the thigh, the largest bone in the human body.' },
    { word: 'TIBIA', definition: 'The larger of the two shin bones, below the knee.' },
    { word: 'FIBULA', definition: 'The thinner bone of the lower leg, alongside the tibia.' },
    { word: 'ULNA', definition: 'The forearm bone on the little-finger side.' },
    { word: 'RADIUS', definition: 'The forearm bone on the thumb side.' },
    { word: 'PELVIS', definition: 'The bony ring at the base of the spine that supports the trunk.' },
    { word: 'SACRUM', definition: 'The triangular bone at the base of the spine, between the hip bones.' },
    { word: 'CARPAL', definition: 'Relating to the eight small bones of the wrist.' },
    { word: 'TARSUS', definition: 'The cluster of bones forming the ankle and upper foot.' },
    { word: 'PHALANX', definition: 'Any of the bones that make up the fingers or toes.' },
    { word: 'PATELLA', definition: 'The kneecap, a small bone in front of the knee joint.' },
    { word: 'SCAPULA', definition: 'The shoulder blade, a flat triangular bone on the upper back.' },
    { word: 'HUMERUS', definition: 'The long bone of the upper arm, from shoulder to elbow.' },
    { word: 'CRANIUM', definition: 'The part of the skull that encloses the brain.' },
    { word: 'STERNUM', definition: 'The breastbone, in the centre of the chest.' },
    { word: 'MANDIBLE', definition: 'The lower jawbone, the only movable bone of the skull.' },
    { word: 'CLAVICLE', definition: 'The collarbone, connecting the arm to the trunk.' },
    { word: 'VERTEBRA', definition: 'One of the small bones that form the spinal column.' },
    { word: 'XIPHOID', definition: 'The small cartilage tip at the lower end of the sternum.' },
    { word: 'ACROMION', definition: 'The bony point at the top of the shoulder blade.' }
  ],
  Nursing: [
    { word: 'TRIAGE', definition: 'Sorting patients by the urgency of their need for care.' },
    { word: 'VITALS', definition: 'Core measurements such as pulse, temperature, breathing and blood pressure.' },
    { word: 'STERILE', definition: 'Completely free of living microorganisms.' },
    { word: 'DOSAGE', definition: 'The size and frequency of a dose of medication.' },
    { word: 'PATIENT', definition: 'A person receiving medical care.' },
    { word: 'DRESSING', definition: 'A covering applied to a wound to protect and help it heal.' },
    { word: 'CATHETER', definition: 'A thin tube inserted into the body to drain or administer fluids.' },
    { word: 'INJECTION', definition: 'Delivering a substance into the body using a needle and syringe.' },
    { word: 'BANDAGE', definition: 'A strip of material used to bind or support an injury.' },
    { word: 'HYGIENE', definition: 'Practices that keep the body and surroundings clean to prevent illness.' },
    { word: 'CAREPLAN', definition: 'A documented plan outlining a patient\u2019s nursing goals and interventions.' },
    { word: 'HANDOVER', definition: 'Passing patient information from one care team to the next shift.' },
    { word: 'MOBILITY', definition: 'A patient\u2019s ability to move around independently.' },
    { word: 'ANALGESIA', definition: 'Relief from pain, often produced by medication.' },
    { word: 'DISCHARGE', definition: 'The formal release of a patient from hospital care.' },
    { word: 'ASSESSMENT', definition: 'A structured evaluation of a patient\u2019s condition and needs.' },
    { word: 'DELEGATION', definition: 'Assigning parts of patient care to another qualified team member.' },
    { word: 'WOUNDCARE', definition: 'Cleaning, dressing and monitoring an injury as it heals.' },
    { word: 'OBSERVATION', definition: 'Regularly monitoring a patient\u2019s condition and vital signs.' },
    { word: 'VENIPUNCTURE', definition: 'Puncturing a vein, usually to draw blood or start an IV line.' }
  ],
  'Medical Laboratory Science': [
    { word: 'SERUM', definition: 'The clear fluid left after blood clots and cells are removed.' },
    { word: 'PLASMA', definition: 'The liquid part of blood that carries cells, proteins and nutrients.' },
    { word: 'CULTURE', definition: 'Growing microorganisms under controlled conditions for study.' },
    { word: 'REAGENT', definition: 'A substance used to trigger or measure a chemical reaction.' },
    { word: 'PIPETTE', definition: 'A slender tube used to measure and transfer small liquid volumes.' },
    { word: 'STAINING', definition: 'Applying dye to a specimen to make structures visible under a microscope.' },
    { word: 'PLATELET', definition: 'A small blood cell fragment that helps blood clot.' },
    { word: 'SPECIMEN', definition: 'A sample of tissue or fluid taken for laboratory examination.' },
    { word: 'LEUKOCYTE', definition: 'A white blood cell that helps fight infection.' },
    { word: 'HEMATOLOGY', definition: 'The study of blood and blood-forming tissues.' },
    { word: 'MICROSCOPE', definition: 'An instrument used to magnify very small objects for viewing.' },
    { word: 'URINALYSIS', definition: 'Laboratory testing of a urine sample.' },
    { word: 'PIPELINE', definition: 'Not typically a lab term, but sometimes used for workflow steps.' },
    { word: 'PIPETMAN', definition: 'A common brand name colloquially used for a lab pipette.' },
    { word: 'CENTRIFUGE', definition: 'A machine that spins samples rapidly to separate their components.' },
    { word: 'CALIBRATION', definition: 'Adjusting an instrument so its readings are accurate.' },
    { word: 'CROSSMATCH', definition: 'Testing donor and recipient blood for compatibility before transfusion.' },
    { word: 'HEMOGLOBIN', definition: 'The oxygen-carrying protein found in red blood cells.' },
    { word: 'COAGULATION', definition: 'The process by which blood thickens and clots.' },
    { word: 'ELECTROLYTE', definition: 'A mineral in blood, such as sodium or potassium, that carries an electric charge.' },
    { word: 'ERYTHROCYTE', definition: 'A red blood cell, which carries oxygen through the body.' },
    { word: 'ANTICOAGULANT', definition: 'A substance that prevents or slows blood clotting.' }
  ],
  Medicine: [
    { word: 'CLINIC', definition: 'A facility where outpatients receive medical care.' },
    { word: 'ACUTE', definition: 'Describes a condition with a sudden onset and short course.' },
    { word: 'CHRONIC', definition: 'Describes a condition that persists over a long period.' },
    { word: 'THERAPY', definition: 'Treatment intended to relieve or heal a disorder.' },
    { word: 'SYMPTOM', definition: 'A sign of illness noticed and reported by the patient.' },
    { word: 'SURGERY', definition: 'Treatment of disease or injury by operative procedures.' },
    { word: 'PATIENT', definition: 'A person receiving medical treatment.' },
    { word: 'DOSAGE', definition: 'The amount and frequency of medicine given.' },
    { word: 'VACCINE', definition: 'A preparation that trains the immune system to resist a disease.' },
    { word: 'SYNDROME', definition: 'A group of symptoms that consistently occur together.' },
    { word: 'REFERRAL', definition: 'Sending a patient to another specialist or service for care.' },
    { word: 'INFECTION', definition: 'Invasion of the body by disease-causing microorganisms.' },
    { word: 'DIAGNOSIS', definition: 'Identifying a disease from its signs and symptoms.' },
    { word: 'PROGNOSIS', definition: 'The likely course and outcome of a disease.' },
    { word: 'ANALGESIC', definition: 'A medicine that relieves pain.' },
    { word: 'TREATMENT', definition: 'Medical care given to combat a disease or condition.' },
    { word: 'ANTIBIOTIC', definition: 'A medicine that kills or slows the growth of bacteria.' },
    { word: 'OUTPATIENT', definition: 'A patient treated without being admitted to hospital.' },
    { word: 'PALLIATIVE', definition: 'Care focused on comfort rather than curing a disease.' },
    { word: 'COMORBIDITY', definition: 'The presence of one or more extra conditions alongside a primary disease.' }
  ],
  Physiology: [
    { word: 'CARDIAC', definition: 'Relating to the heart.' },
    { word: 'NEURON', definition: 'A nerve cell that transmits electrical signals in the body.' },
    { word: 'SYNAPSE', definition: 'The junction where signals pass from one neuron to another.' },
    { word: 'HORMONE', definition: 'A chemical messenger released into the blood to regulate body functions.' },
    { word: 'REFLEX', definition: 'An automatic response to a stimulus, without conscious thought.' },
    { word: 'OSMOSIS', definition: 'Movement of water across a membrane toward higher solute concentration.' },
    { word: 'PERFUSION', definition: 'The flow of blood through tissue to deliver oxygen and nutrients.' },
    { word: 'DIFFUSION', definition: 'Movement of particles from an area of high to low concentration.' },
    { word: 'EXCRETION', definition: 'Removal of waste products from the body.' },
    { word: 'ABSORPTION', definition: 'The uptake of substances into cells, blood, or tissue.' },
    { word: 'HOMEOSTASIS', definition: 'The body\u2019s process of maintaining a stable internal environment.' },
    { word: 'METABOLISM', definition: 'The chemical processes that keep an organism alive and functioning.' },
    { word: 'RESPIRATION', definition: 'The process of exchanging oxygen and carbon dioxide in the body.' },
    { word: 'FILTRATION', definition: 'The process of removing substances from blood, chiefly in the kidney.' },
    { word: 'CONTRACTION', definition: 'The shortening of a muscle fibre to produce movement or force.' },
    { word: 'VENTILATION', definition: 'The movement of air into and out of the lungs.' },
    { word: 'CIRCULATION', definition: 'The continuous movement of blood through the heart and vessels.' },
    { word: 'PERISTALSIS', definition: 'Wave-like muscle contractions that move contents through the digestive tract.' },
    { word: 'BARORECEPTOR', definition: 'A sensor that detects pressure changes in blood vessels.' },
    { word: 'THERMOREGULATION', definition: 'The body\u2019s process of maintaining a stable internal temperature.' }
  ],
  Biology: [
    { word: 'CELL', definition: 'The smallest structural and functional unit of a living organism.' },
    { word: 'GENE', definition: 'A segment of DNA that carries instructions for a trait.' },
    { word: 'DNA', definition: 'The molecule that carries genetic instructions in living things.' },
    { word: 'ENZYME', definition: 'A protein that speeds up chemical reactions in the body.' },
    { word: 'TISSUE', definition: 'A group of similar cells performing a specific function.' },
    { word: 'PROTEIN', definition: 'A large molecule made of amino acids, essential for body structure and function.' },
    { word: 'MITOSIS', definition: 'Cell division that produces two identical daughter cells.' },
    { word: 'MEIOSIS', definition: 'Cell division that produces reproductive cells with half the chromosomes.' },
    { word: 'NUCLEUS', definition: 'The membrane-bound structure in a cell that holds its DNA.' },
    { word: 'ORGANISM', definition: 'Any individual living thing.' },
    { word: 'MUTATION', definition: 'A change in the DNA sequence of a gene.' },
    { word: 'HEREDITY', definition: 'The passing of traits from parents to offspring.' },
    { word: 'RIBOSOME', definition: 'A cell structure that builds proteins.' },
    { word: 'MEMBRANE', definition: 'The thin barrier that encloses a cell and controls what enters or leaves.' },
    { word: 'CYTOPLASM', definition: 'The jelly-like substance filling a cell around its nucleus.' },
    { word: 'ECOSYSTEM', definition: 'A community of organisms interacting with their environment.' },
    { word: 'ORGANELLE', definition: 'A specialised structure inside a cell with a specific function.' },
    { word: 'EVOLUTION', definition: 'The gradual change in species over successive generations.' },
    { word: 'CHROMOSOME', definition: 'A thread-like structure of DNA that carries genetic information.' },
    { word: 'PHOTOSYNTHESIS', definition: 'The process by which plants convert light into chemical energy.' }
  ],
  Pharmacology: [
    { word: 'DRUG', definition: 'A substance used to diagnose, treat, or prevent disease.' },
    { word: 'DOSAGE', definition: 'The measured amount and frequency of a medicine.' },
    { word: 'ADVERSE', definition: 'Describes an unwanted or harmful effect of a treatment.' },
    { word: 'AGONIST', definition: 'A substance that activates a receptor to produce a response.' },
    { word: 'POTENCY', definition: 'The amount of a drug needed to produce a given effect.' },
    { word: 'RECEPTOR', definition: 'A cell structure that binds to a drug or signalling molecule.' },
    { word: 'HALFLIFE', definition: 'The time it takes for half a drug dose to leave the body.' },
    { word: 'OVERDOSE', definition: 'Taking more of a substance than is safe for the body.' },
    { word: 'TOXICITY', definition: 'The degree to which a substance can harm the body.' },
    { word: 'ANTAGONIST', definition: 'A substance that blocks a receptor and prevents a response.' },
    { word: 'TOLERANCE', definition: 'A reduced response to a drug after repeated use.' },
    { word: 'ABSORPTION', definition: 'How a drug moves from its site of administration into the blood.' },
    { word: 'EXCIPIENT', definition: 'An inactive substance that carries the active ingredient in a medicine.' },
    { word: 'METABOLISM', definition: 'The body\u2019s chemical breakdown of a drug.' },
    { word: 'ELIMINATION', definition: 'The removal of a drug and its by-products from the body.' },
    { word: 'INTERACTION', definition: 'An effect that occurs when two or more drugs are taken together.' },
    { word: 'PRESCRIPTION', definition: 'A written instruction from a licensed provider to obtain medication.' },
    { word: 'FORMULATION', definition: 'The way a drug is prepared, such as a tablet or liquid.' },
    { word: 'BIOAVAILABILITY', definition: 'The proportion of a drug that reaches the bloodstream unchanged.' },
    { word: 'PHARMACOKINETICS', definition: 'The study of how the body absorbs, distributes and clears a drug.' }
  ],
  Pathology: [
    { word: 'BIOPSY', definition: 'Removing a small sample of tissue for examination.' },
    { word: 'LESION', definition: 'An area of tissue damaged by injury or disease.' },
    { word: 'TUMOR', definition: 'An abnormal mass of tissue formed by excessive cell growth.' },
    { word: 'EDEMA', definition: 'Swelling caused by excess fluid trapped in body tissue.' },
    { word: 'BENIGN', definition: 'Not cancerous; not likely to spread or become life-threatening.' },
    { word: 'ATROPHY', definition: 'The wasting away or shrinking of a body tissue.' },
    { word: 'AUTOPSY', definition: 'An examination of a body after death to determine the cause.' },
    { word: 'DISEASE', definition: 'A disorder of structure or function in the body.' },
    { word: 'ETIOLOGY', definition: 'The cause or origin of a disease.' },
    { word: 'ISCHEMIA', definition: 'A restricted blood supply to a tissue, causing a shortage of oxygen.' },
    { word: 'NECROSIS', definition: 'The death of cells or tissue in a living organism.' },
    { word: 'FIBROSIS', definition: 'The thickening or scarring of connective tissue.' },
    { word: 'MALIGNANT', definition: 'Cancerous, and capable of invading nearby tissue or spreading.' },
    { word: 'DIAGNOSIS', definition: 'Identifying a disease by examining its signs and symptoms.' },
    { word: 'NEOPLASM', definition: 'An abnormal growth of tissue, benign or malignant.' },
    { word: 'GRANULOMA', definition: 'A small area of inflammation caused by infection or foreign material.' },
    { word: 'INFARCTION', definition: 'Tissue death due to an interrupted blood supply.' },
    { word: 'METASTASIS', definition: 'The spread of cancer cells from the original site to other parts of the body.' },
    { word: 'HYPERPLASIA', definition: 'An abnormal increase in the number of cells in a tissue.' },
    { word: 'INFLAMMATION', definition: 'The body\u2019s protective response to injury or infection, with redness and swelling.' }
  ],
  Microbiology: [
    { word: 'VIRUS', definition: 'A microscopic infectious agent that replicates inside living cells.' },
    { word: 'SPORE', definition: 'A dormant, resistant form some microorganisms use to survive harsh conditions.' },
    { word: 'FUNGUS', definition: 'An organism such as yeast or mold that can cause infection.' },
    { word: 'MICROBE', definition: 'A microscopic living organism, such as bacteria or a virus.' },
    { word: 'TOXIN', definition: 'A poisonous substance produced by a living organism.' },
    { word: 'COLONY', definition: 'A visible cluster of microorganisms grown from a single cell.' },
    { word: 'BIOFILM', definition: 'A protective layer of microorganisms attached to a surface.' },
    { word: 'BACTERIA', definition: 'Single-celled microorganisms, some of which cause disease.' },
    { word: 'PATHOGEN', definition: 'Any organism capable of causing disease.' },
    { word: 'PARASITE', definition: 'An organism that lives on or in a host and benefits at its expense.' },
    { word: 'PROTOZOA', definition: 'Single-celled microorganisms, some of which are parasitic.' },
    { word: 'CULTURE', definition: 'Growing microorganisms in a controlled environment for study.' },
    { word: 'VIRULENCE', definition: 'The severity or harmfulness of a disease-causing organism.' },
    { word: 'GRAMSTAIN', definition: 'A staining method used to classify bacteria by their cell wall.' },
    { word: 'RESISTANCE', definition: 'The ability of a microorganism to survive a drug meant to kill it.' },
    { word: 'INFECTION', definition: 'The invasion and multiplication of microorganisms in the body.' },
    { word: 'MUTUALISM', definition: 'A relationship in which two organisms both benefit from living together.' },
    { word: 'ANTIBIOTIC', definition: 'A medicine that kills or inhibits the growth of bacteria.' },
    { word: 'INOCULATION', definition: 'Introducing a microorganism into a culture medium or the body.' },
    { word: 'STERILIZATION', definition: 'A process that destroys all forms of microbial life.' }
  ],
  Biochemistry: [
    { word: 'ATP', definition: 'The molecule cells use to store and transfer chemical energy.' },
    { word: 'DNA', definition: 'The molecule that stores genetic instructions in cells.' },
    { word: 'RNA', definition: 'A molecule that helps translate DNA instructions into proteins.' },
    { word: 'UREA', definition: 'A waste product formed from protein breakdown and excreted in urine.' },
    { word: 'LIPID', definition: 'A fat or fat-like molecule used for energy storage and cell membranes.' },
    { word: 'ENZYME', definition: 'A protein that speeds up chemical reactions in the body.' },
    { word: 'BUFFER', definition: 'A solution that resists changes in pH when acid or base is added.' },
    { word: 'PEPTIDE', definition: 'A short chain of amino acids linked together.' },
    { word: 'PROTEIN', definition: 'A large molecule built from amino acids, vital for body structure and function.' },
    { word: 'CATALYST', definition: 'A substance that speeds up a reaction without being consumed.' },
    { word: 'HORMONE', definition: 'A chemical messenger that regulates processes in the body.' },
    { word: 'GLUCOSE', definition: 'A simple sugar that is the body\u2019s main source of energy.' },
    { word: 'OXIDATION', definition: 'A chemical reaction involving the loss of electrons.' },
    { word: 'PHOSPHATE', definition: 'A chemical group involved in energy transfer and DNA structure.' },
    { word: 'SUBSTRATE', definition: 'The molecule an enzyme acts upon during a reaction.' },
    { word: 'AMINOACID', definition: 'A building block molecule that links together to form proteins.' },
    { word: 'GLYCOLYSIS', definition: 'The metabolic pathway that breaks down glucose to release energy.' },
    { word: 'ELECTROLYTE', definition: 'A mineral, such as sodium or potassium, that carries an electric charge in fluid.' },
    { word: 'METABOLISM', definition: 'The set of chemical reactions that sustain life in an organism.' },
    { word: 'CHOLESTEROL', definition: 'A waxy lipid used to build cell membranes and hormones.' }
  ],
  Histology: [
    { word: 'STROMA', definition: 'The connective, structural tissue that supports an organ.' },
    { word: 'GLAND', definition: 'An organ that produces and releases substances such as hormones.' },
    { word: 'TENDON', definition: 'A tough band of tissue that connects muscle to bone.' },
    { word: 'MUSCLE', definition: 'Tissue composed of fibres that contract to produce movement.' },
    { word: 'NEURON', definition: 'A nerve cell that transmits electrical signals.' },
    { word: 'TISSUE', definition: 'A group of similar cells that perform a shared function.' },
    { word: 'MATRIX', definition: 'The material surrounding cells within a tissue, giving it structure.' },
    { word: 'KERATIN', definition: 'A tough protein found in skin, hair, and nails.' },
    { word: 'NUCLEUS', definition: 'The structure within a cell that houses its DNA.' },
    { word: 'ADIPOSE', definition: 'Fatty tissue that stores energy and cushions organs.' },
    { word: 'COLLAGEN', definition: 'A structural protein found in skin, bone, and connective tissue.' },
    { word: 'OSTEOCYTE', definition: 'A mature bone cell embedded within bone tissue.' },
    { word: 'SECRETION', definition: 'The release of a substance produced by a cell or gland.' },
    { word: 'CARTILAGE', definition: 'Flexible connective tissue found in joints, the ear, and nose.' },
    { word: 'CYTOPLASM', definition: 'The gel-like substance filling a cell around its nucleus.' },
    { word: 'FIBROBLAST', definition: 'A cell that produces collagen and other connective tissue fibres.' },
    { word: 'EPITHELIUM', definition: 'The thin tissue that lines body surfaces and cavities.' },
    { word: 'MELANOCYTE', definition: 'A cell that produces the pigment melanin in the skin.' },
    { word: 'CHONDROCYTE', definition: 'A cell found in cartilage that maintains its matrix.' },
    { word: 'ENDOTHELIUM', definition: 'The thin layer of cells lining blood vessels.' }
  ],
  Immunology: [
    { word: 'PLASMA', definition: 'The liquid part of blood that carries antibodies and nutrients.' },
    { word: 'VACCINE', definition: 'A preparation that trains the immune system to fight a specific disease.' },
    { word: 'ANTIGEN', definition: 'A molecule that triggers an immune response.' },
    { word: 'ANTIBODY', definition: 'A protein made by the immune system to target a specific antigen.' },
    { word: 'IMMUNITY', definition: 'The body\u2019s ability to resist a particular infection or toxin.' },
    { word: 'ALLERGEN', definition: 'A substance that causes an allergic reaction.' },
    { word: 'CYTOKINE', definition: 'A small protein used by cells to signal the immune system.' },
    { word: 'TOLERANCE', definition: 'The immune system\u2019s ability to not react against the body\u2019s own tissue.' },
    { word: 'PHAGOCYTE', definition: 'An immune cell that engulfs and destroys pathogens or debris.' },
    { word: 'NEUTROPHIL', definition: 'A common type of white blood cell that fights infection.' },
    { word: 'COMPLEMENT', definition: 'A group of blood proteins that help destroy pathogens.' },
    { word: 'AUTOIMMUNE', definition: 'Describes a condition where the immune system attacks the body\u2019s own cells.' },
    { word: 'LYMPHOCYTE', definition: 'A type of white blood cell central to the immune response.' },
    { word: 'MACROPHAGE', definition: 'A large immune cell that engulfs pathogens and debris.' },
    { word: 'VACCINATION', definition: 'The act of administering a vaccine to build immunity.' },
    { word: 'INFLAMMATION', definition: 'The immune system\u2019s protective response to injury or infection.' },
    { word: 'INTERLEUKIN', definition: 'A type of cytokine that helps immune cells communicate.' },
    { word: 'BLYMPHOCYTE', definition: 'An immune cell that matures to produce antibodies.' },
    { word: 'TLYMPHOCYTE', definition: 'An immune cell that directly attacks infected cells.' },
    { word: 'IMMUNOGLOBULIN', definition: 'Another name for an antibody, produced by B lymphocytes.' }
  ]
};

export const CATEGORY_NAMES = Object.keys(CATEGORY_WORDS);
